compression: lzma
verbosity: 1

source_directories:
  - /volumes/vaultwarden-data

archive_name_format: "{hostname}-{now:%Y-%m-%dT%H:%M:%S}" # ISO/Unix style

repositories:
  - path: /volumes/backup-local-borg/
    label: local

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

checks:
  - name: repository
  - name: archives
    frequency: 2 weeks

apprise:
  states:
    - finish
    - fail
  send_logs: true
  services:
    - url: "mailtos://${SMTP_USER}:${SMTP_PASS}@smtp.gmail.com:${SMTP_PORT}?to=${SMTP_TO}&name=Borgmatic&starttls=yes || exit 1"
      label: alerta-email

commands:
  - after: repository
    states:
      - finish
    run:
      - rclone sync /volumes/backup-local-borg/ gcp-storage:BACKUP-VOLUMES --config /root/.config/rclone/rclone.conf
