# Define o usuário para evitar erros de permissão de pasta
su root root

# Configurações padrão seguras
compress
missingok
notifempty

# Regras específicas para os logs do Borg
/var/log/borg/*.log {
    monthly
    rotate 12
    copytruncate
}